<?php

/**
 * @file
 * Contains grupoite.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function grupoite_tools_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_grupoite_tools_user_login_form_submit';
}

/**
 * Custom submit handler for login form.
 */
function _grupoite_tools_user_login_form_submit($form, FormStateInterface $form_state) {
  // Set redirect to login form.
  $form_state->setRedirect('system.admin_content');
}

